---
blank_issues_enabled: false
contact_links:
  - name: YiriMirai OneBot Community Support
    url: https://github.com/YiriMiraiProject/YiriMiraiOneBot/discussions
    about: Please ask and answer questions here.
